### ISSUE TITLE
Redundant binary upload after uploading build with deliver.

### ISSUE THREAD

**Issue by thebugcode** [fastlane/pilot#104]
After uploading a build to iTunes connect using deliver I want to make it available to  testflight testers.
It seems that the way to do that is using pilot upload, which fails because the build was already uploaded using deliver. Is there a way to achieve this?

**Comment by KrauseFx** [comment]
Yeah, you should use `fastlane` to increment the build number and call `pilot` from there

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1887. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
