### ISSUE TITLE
Pilot does not add tester to Internal Testing

### ISSUE THREAD

**Issue by chappejw** [fastlane/pilot#111]
When a user exists in Internal or External testers we can use Pilot to remove the user like this

    pilot remove -u "user@domain.com" -a "com.Company.NextApp" -e "someuser@domain.com" -r "Company Name Inc"

But when adding the user back there is no way to concretely specify that this is an Internal User unless by specifically not passing the flag --distribute_external like this

    pilot add -u "user@domain.com" -a "com.Company.NextApp" -f "FirstName" -l "LastName" -e "someuser@domain.com" -r "Company Name Inc"

When adding the user the account is added to External Testing, but instead I want to force Pilot to add the user to Internal Testing, especially for our in house iTunesconnect. Is this possible? Or does this depend on anything?

**Comment by vandadnp** [comment]
Any updates on this?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1885. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:

**Comment by chappejw** [comment]
Hello Fastlaners,

As a workaround, developers may have to decide if they want to use a
password instead of not setting a password or instead of setting a blank
password. I would preferably want to be able to set an empty or blank
password though, but this issue is long outstanding now and there seems to
be no solution other than to create the push certificates manually with a
blank or empty password.

Jacob
