### ISSUE TITLE
Please add support for declaring all ITC TestFlight submission fields

### ISSUE THREAD

**Issue by NikolaiSa** [fastlane/pilot#119]
--changelog is for "What to Test"

Please add:

App Description 
Feedback Email
Marketing URL
Privacy Policy URL

**Comment by ffittschen** [comment]
The `--changelog` is also mentioned here: https://github.com/fastlane/pilot/issues/86

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1882. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
