### ISSUE TITLE
Pilot incorrectly identifies build as "Expired"

### ISSUE THREAD

**Issue by ChristopherDrum** [fastlane/pilot#126]
I have a build that is currently available only to External Testing. When I run `pilot builds` that build is marked as "Expired" in the output. A screenshot shows it clearly; note version 3.0.2, build 3.0.2.2, please.
![screen shot 2016-01-26 at 11 12 24 am](https://cloud.githubusercontent.com/assets/320377/12570782/16c31010-c41e-11e5-99ad-4abcfc1504ac.png)

**Comment by macecchi** [comment]
I'm having the same issue, but in my case the correct build was supposed to be Processing. Instead, it shows 'Expired' (twice!)

![screen shot 2016-02-06 at 16 10 05](https://cloud.githubusercontent.com/assets/5282467/12868358/362c0138-ccec-11e5-953b-c790e6ac7bae.png)
![screen shot 2016-02-06 at 16 11 07](https://cloud.githubusercontent.com/assets/5282467/12868362/4172ae34-ccec-11e5-984d-691e49d3f38b.png)

Using pilot 1.3.0.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1881. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
