### ISSUE TITLE
It would be nice to be able to list testers based on which version they have installed

### ISSUE THREAD

**Issue by knutigro** [fastlane/pilot#140]
I have lots of Testers who don't install my builds and want to be able to easily list all people with a certain build.

Maybe it would be possible to add some parameters to the list command? 

I would be happy to do this as a little ruby excersize for myselves.

**Comment by vpolouchkine** [comment]
Go for it. 👍

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1878. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
