### ISSUE TITLE
Pilot does not show installed versions at all for specific app

### ISSUE THREAD

**Issue by appcoders** [fastlane/pilot#150]
This is the iTunes Connect state:

https://www.dropbox.com/s/4i7saiv85qhztse/itunesconnect.png?dl=0

This is what pilot gives me for this app (all users are there):

https://www.dropbox.com/s/d2nun5q7totc11l/pilot_console.png?dl=0

**Comment by vpolouchkine** [comment]
Can you please share the version of `pilot` you're running?

**Comment by appcoders** [comment]
it's pilot 1.4.1

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1876. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
