### ISSUE TITLE
How to start testing with selected internal tester(s)?

### ISSUE THREAD

**Issue by billypchan** [fastlane/pilot#21]
Hello Felix,
Thank you very much for your great job!
I have a question: Is it possible to use Pilot to distribute the app to one of the internal testers only?

Regard,
Bill

**Comment by KrauseFx** [comment]
Hi @billypchan, it's possible to upload the build. You'll have to manually enable distribution to internal testers.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1920. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
