### ISSUE TITLE
Switch TestFlight off for apps in iTunes Connect?

### ISSUE THREAD

**Issue by sarthak03** [fastlane/pilot#25]
Is there a way `pilot` can be used to switch off TestFlight for selected apps on iTunes Connect. As I have noticed iTunes Connect doesn't allow more than 10 apps to be under TestFlight mode at the same time.

**Comment by KrauseFx** [comment]
Sorry, that's not possible with `pilot`

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1918. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
