### ISSUE TITLE
Submit without Bitcode

### ISSUE THREAD

**Issue by iv-mexx** [fastlane/pilot#43]
After solving my problems from in #42 I ran right into the next one: After uploading the .ipa to the AppStore, I get an email from iTunesConnect:

> Invalid Bundle - Failed to verify bitcode in ReactiveCocoa.framework/ReactiveCocoa: error: Bundle only contains bitcode-marker qonnect scan.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa (armv7) ...

(listing all the Frameworks that I've included via Carthage)

When uploading the same archive from Xcode directly, I need to uncheck the "Include Bitcode" checkmark, otherwise I get the same errors. With that checkmark unchecked, it works from Xcode. 

![screen shot 2015-09-30 at 19 05 46](https://cloud.githubusercontent.com/assets/3407787/10200943/a6f29614-67a9-11e5-934b-42673c55d662.png)

I'm not sure if this option needs to be available in pilot as well, or if something else is the problem again.

**Comment by jarz** [comment]
Looks like this is being discussed @ Carthage https://github.com/Carthage/Carthage/issues/535

**Comment by NachoSoto** [comment]
Similar to this, I was wondering if there's an option to disable uploading the `DSYM` (the "Include app symbols..." checkbox), since that's currently broken in Xcode 7.1 beta 2 🔥

<img width="485" alt="screen shot 2015-10-04 at 22 44 52" src="https://cloud.githubusercontent.com/assets/685609/10273725/8dc580a0-6ae9-11e5-9dff-0f0829b5f9db.png">

**Comment by KrauseFx** [comment]
@NachoSoto Of course, if you're using [gym](https://github.com/fastlane/gym) to build your application the following options are available (`gym --help`)

```
    -m, --include_symbols  Should the ipa file include symbols? (GYM_INCLUDE_SYMBOLS)
    -z, --include_bitcode  Should the ipa include bitcode? (GYM_INCLUDE_BITCODE)
```

You can then upload the build using [deliver](https://github.com/KrauseFx/deliver) or [pilot](https://github.com/fastlane/pilot)

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1912. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
