### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by ahknight** [fastlane/pilot#46]
We use the user groups functionality in iTunes Connect for our beta tests a lot.  I don't see support for that in pilot at the moment.  Am I missing it?

What we do is recruit a set of testers, add them to the iTunes account in a user group ("MyApp Beta 1") and then add the group to the app.  This way we know which tests a user is on, and also why they're on the account in the first place (we have many, many apps in the account).

Is there a way to specify a group when importing a CSV so that the user is also added to that group (and have it created if it doesn't exist)?

**Comment by KrauseFx** [comment]
Choosing a group in `pilot` is not possible right now.

**Comment by ahknight** [comment]
Any plans?

**Comment by KrauseFx** [comment]
I'm not working on it right now, sorry.

**Comment by ilyas-hallak** [comment]
+1

**Comment by maxoly** [comment]
+1

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1911. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
