### ISSUE TITLE
Filter testers by the app

### ISSUE THREAD

**Issue by kostiakoval** [fastlane/pilot#52]
## New feature request: 

I Want to be able to filter the testers by the app ID.
`pilot list -a no.myCompanyID.MyappID`

**Comment by Gargam** [comment]
+1

**Comment by jaleksynas** [comment]
I think this mostly works now. #123 

Internal testers list still not filtered properly when using a non-admin account (it may be correctly filtered with the admin account though [citation needed]).  More info about admin account permission issues are here #85.

External testers filters by app correctly in either case.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1909. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
