### ISSUE TITLE
REGARDING_PRODUCE

### ISSUE THREAD

**Issue by parthitheindian** [fastlane/pilot#58]
Hi All,
         I was trying to upload the App to iTunesConnect with "PRODUCE" using the following command

produce -u username -a app-id -d -q app-name -z '1.0'

But, the above command throws that App Name Already been Used. Actually, it was never used. Could you point out any error in the above command? Thanks.

**Comment by KrauseFx** [comment]
Please post the full stack trace and output. But it probably means that the name on iTunes Connect is already taken. Try creating the app on iTunes Connect.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1907. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
