### ISSUE TITLE
Submit for Beta Review

### ISSUE THREAD

**Issue by kohtenko** [fastlane/pilot#60]
What about submitting to external beta review in `pilot`? 
This available in `spaceship` with `build.submit_for_beta_review!(parameters)`, but never used in `pilot`.

**Comment by KrauseFx** [comment]
Currently not implemented in `pilot`

**Comment by maciekish** [comment]
+1

**Comment by bjornoss** [comment]
+1

**Comment by cmds4410** [comment]
+1 :)

**Comment by jorgeazevedo** [comment]
+1 this would be a great one to have! @kohtenko do you know how to call spaceship directly?

**Comment by kohtenko** [comment]
@jorgeazevedo https://github.com/fastlane/spaceship/blob/master/docs/iTunesConnect.md#builds

**Comment by jorgeazevedo** [comment]
Ah brilliant, thanks!

**Comment by jorgeazevedo** [comment]
@kohtenko I was just getting ready to code some ruby, but I just used pilot to submit a beta and it submitted, waited for beta review, and pushed it out to external users. Out of its own volition!

Here's what I used

    pilot upload --changelog"" --username "" --app_identifier ""

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1905. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
