### ISSUE TITLE
Find (or preferably remove) users with no devices.

### ISSUE THREAD

**Issue by runloop** [fastlane/pilot#61]
Seeing as Apple seem to be actively worsening the experience and functionality of the iTC version of TestFlight it would be amazing if Pilot allowed us to find users with no devices, or better yet, simply remove them. I've got 500 or so users they have been invited to test and probably 80% haven't even registered their device. Currently there is no sane way to remove these users from TestFlight. I'm hoping one day Pilot could be the answer.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1904. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
