### ISSUE TITLE
pilot upload --ipa doesn't submit the beta

### ISSUE THREAD

**Issue by maciekish** [fastlane/pilot#64]
Hi, If i run `pilot upload --ipa /path/to/app.ipa` it says that the app was uploaded and distributed but neither internal nor external testers get the beta.

Output:

- Distributing new build to testers
- Successfully distribute build to beta testers 🚀

I can see the uploaded version in iTunes Connect but nothing is assigned in internal or external testing.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1902. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
