### ISSUE TITLE
xcarchive support?

### ISSUE THREAD

**Issue by Pipen** [fastlane/pilot#73]
Hi, Correct me if I'm wrong, but the only way to upload dSYM to iTunes Connect/Testflight is by instead of uploading an IPA would be to upload a xcarchive like xcode does for you, instead of using the application loader which seems to have very limited support now days.

**Comment by KrauseFx** [comment]
Sorry, I don't know, I'm using a third party crash reporter instead (e.g. Crashlytics)

**Comment by KrauseFx** [comment]
With Bitcode, Apple compiles your app anyway and should have your symbolication files as far as I konw.

**Comment by bassrock** [comment]
If you look here when you submit an archive it has an option to include app symbols. With the bit code you will only get the dsyms for the new builds apple creates it seems not the initial one you upload. 

https://developer.apple.com/library/ios/recipes/xcode_help-archives_organizer/articles/UploadingYourApp.html

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1900. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
