### ISSUE TITLE
Password that starts with a '-' recognized as an option

### ISSUE THREAD

**Issue by RuCray** [fastlane/pilot#83]
Password that starts with a `-` is recognized as an option and the upload process is stalled with the warning message: 
`[Transporter Warning Output]: The following option was specified but is not recognized:`

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1897. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
