### ISSUE TITLE
Distribute to all testers

### ISSUE THREAD

**Issue by FelipeDocil** [fastlane/pilot#9]
This is actually a suggestion/question than a issue,

> This tool allows you to manage all important features of Apple TestFlight using your terminal.
>
> Upload new builds and distribute them to all testers

There's a way to only Distribute to all testers, instead of upload another .ipa file and then distribute?

If I opt only to submit to Itunes Connect but not distribute, and later I want distribute.
So I'd like a way to distribute to Internal Tester and External Tester a build is already at Itunes Connect. And handle *Submit for Beta App Review*

Thank you!

**Comment by KrauseFx** [comment]
Sorry, that's not possible right now with `pilot`. You could build something like that using `spaceship` though :+1:

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1922. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
