### ISSUE TITLE
Feature Request: CSV Export - Split train_version and build_version

### ISSUE THREAD

**Issue by loretoparisi** [fastlane/pilot#93]
Is it possibile to split the ```Installed Version``` column in ```train_version``` and ```build_version``` in order to have two columns like:

```
TrainVersion | BuildVersion
5.1.7 | 2015120101
```

Thank you.

**Comment by KrauseFx** [comment]
Yeah, feel free to submit a pull request changing this, it should be pretty easy to add :+1: Let me know if you need any help

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1890. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
